# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 新冠疫情欧洲中文台
email: ''
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://covid19-zh-eu.github.io" # the base hostname & protocol for your site
author: covid19-zh-eu

telegram_username: covid19_eu_zh_c
github_username:  covid19-eu-zh

# Build settings
markdown: kramdown

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


exclude: ['README.md','README-minima.md','History.markdown', 'Gemfile.lock', 'Gemfile','assets/mermaid/www']



dataset:
    covid-19-de: "https://covid19-eu-data-cache.now.sh/covid-19-de.csv"
    covid-19-at: "https://covid19-eu-data-cache.now.sh/covid-19-at.csv"
    covid-19-fr: "https://covid19-eu-data-cache.now.sh/covid-19-fr.csv"
    covid-19-nl: "https://covid19-eu-data-cache.now.sh/covid-19-nl.csv"
    italy-dpc:   "https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv"
